defaults:
  - model: bert
  - _self_

random_seed: 42
use_cuda_for_train: true

inference:
  use_cuda_for_inference: true
  n_predictions: 5
  n_candidates: 10

  prefer_saved_matrix: true
  references_embeddings_save_path: "model_weights/references_embeddings.pth"